import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Omar Al-Khanji Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav id="main-nav-bar">
          <Link className='navlink' href="./"> 
             Log out
          </Link>
          &nbsp;&nbsp;
          <Link className='navlink' href={"/aboutpage"}>
            about
          </Link>&nbsp;&nbsp;
          <Link className='navlink' href="/projects">
                projects
          </Link>&nbsp;&nbsp;
          <Link className='navlink' href="/contactme">
                contact me
          </Link>
            
        </nav>
        {children}</body>
    </html>
  )
}
