import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav id="main-nav-bar">
        
          <Link className='navlink' href="./"> 
             Log out
          </Link>
        &nbsp;&nbsp;
          <Link className='navlink' href={"/homepage"}>
            Home
          </Link>
          &nbsp;&nbsp;
          <Link className='navlink' href={"/aboutpage"}>
            About
          </Link>&nbsp;&nbsp;
          <Link className='navlink' href="/articles">
                Articles
          </Link>&nbsp;&nbsp;
          <Link className='navlink' href="/posts">
              Posts
          </Link>
            
        </nav>
        {children}</body>
    </html>
  )
}
